id: P8F18E4FF
initial_creation_type: ocr
source_metadata:
  volumes:
    cc9c5a058a724c2a86716d9b812cf412:
      base_file: v120.txt
      image_group_id: I1PD95965
      title: ''
      total_pages: 1865
      volume_number: 120
